# Generated by Django 3.2.6 on 2022-06-26 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_hoghugh', models.CharField(max_length=255, verbose_name='حقوق روزانه')),
                ('monthly_hoghugh', models.CharField(max_length=255, verbose_name='حقوق ماهانه')),
                ('kharbar_maskan', models.CharField(max_length=255, verbose_name='بن خاربار مسکن')),
                ('padash', models.CharField(max_length=255, verbose_name='پاداش')),
                ('ezafe_kar', models.CharField(max_length=255, verbose_name='اضافه کار')),
                ('sayere_mazaya', models.CharField(max_length=255, verbose_name='سایر مزایا')),
                ('nakhalese_pardakhti', models.CharField(max_length=255, verbose_name='ناخالص پرداختی')),
                ('maliat', models.CharField(max_length=255, verbose_name='مالیات')),
                ('haghe_bime', models.CharField(max_length=255, verbose_name='حق بیمه')),
                ('mosaede', models.CharField(max_length=255, verbose_name='مساعده')),
                ('vam', models.CharField(max_length=255, verbose_name='وام')),
                ('sayere_kosurat', models.CharField(max_length=255, verbose_name='سایر کسورات')),
                ('jame_kosurat', models.CharField(max_length=255, verbose_name='جمع کسورات')),
                ('khalese_pardakhti', models.CharField(max_length=255, verbose_name='خالص پرداختی')),
                ('mah', models.CharField(max_length=255, verbose_name='خالص پرداختی')),
                ('code', models.CharField(max_length=255, verbose_name='کد پرسنلی')),
                ('name', models.CharField(max_length=255, verbose_name='نام')),
                ('karkard', models.CharField(max_length=255, verbose_name='کارکرد به روز')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'fish',
                'ordering': ('date_added',),
            },
        ),
    ]
