# Generated by Django 3.2.6 on 2022-06-26 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_fish'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fish',
            name='kharbar_maskan',
        ),
        migrations.AddField(
            model_name='fish',
            name='bon',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='بن'),
        ),
        migrations.AddField(
            model_name='fish',
            name='code_meli',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='کد ملی'),
        ),
        migrations.AddField(
            model_name='fish',
            name='maskan',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='مسکن'),
        ),
        migrations.AddField(
            model_name='fish',
            name='nobate_kari',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='نوبت کاری'),
        ),
        migrations.AddField(
            model_name='fish',
            name='ovlad',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='اولاد'),
        ),
        migrations.AlterField(
            model_name='fish',
            name='code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='کد پرسنلی'),
        ),
        migrations.AlterField(
            model_name='fish',
            name='daily_hoghugh',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='حقوق روزانه'),
        ),
        migrations.AlterField(
            model_name='fish',
            name='ezafe_kar',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='اضافه کار'),
        ),
        migrations.AlterField(
            model_name='fish',
            name='haghe_bime',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='حق بیمه'),
        ),
        migrations.AlterField(
            model_name='fish',
            name='jame_kosurat',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='جمع کسورات'),
        ),
        migrations.AlterField(
            model_name='fish',
            name='karkard',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='کارکرد به روز'),
        ),
        migrations.AlterField(
            model_name='fish',
            name='khalese_pardakhti',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='خالص پرداختی'),
        ),
        migrations.AlterField(
            model_name='fish',
            name='mah',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='خالص پرداختی'),
        ),
        migrations.AlterField(
            model_name='fish',
            name='maliat',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='مالیات'),
        ),
        migrations.AlterField(
            model_name='fish',
            name='monthly_hoghugh',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='حقوق ماهانه'),
        ),
        migrations.AlterField(
            model_name='fish',
            name='mosaede',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='مساعده'),
        ),
        migrations.AlterField(
            model_name='fish',
            name='nakhalese_pardakhti',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ناخالص پرداختی'),
        ),
        migrations.AlterField(
            model_name='fish',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='fish',
            name='padash',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='پاداش'),
        ),
        migrations.AlterField(
            model_name='fish',
            name='sayere_kosurat',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='سایر کسورات'),
        ),
        migrations.AlterField(
            model_name='fish',
            name='sayere_mazaya',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='سایر مزایا'),
        ),
        migrations.AlterField(
            model_name='fish',
            name='vam',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='وام'),
        ),
        migrations.AlterField(
            model_name='messagefile',
            name='msgFile',
            field=models.FileField(max_length=200, upload_to='documents/%Y/%m/%d'),
        ),
    ]
