# Generated by Django 3.2.6 on 2022-06-28 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20220626_1631'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fish',
            name='jame_kosurat',
        ),
        migrations.RemoveField(
            model_name='fish',
            name='khalese_pardakhti',
        ),
        migrations.RemoveField(
            model_name='fish',
            name='nakhalese_pardakhti',
        ),
        migrations.RemoveField(
            model_name='fish',
            name='sayere_kosurat',
        ),
        migrations.RemoveField(
            model_name='fish',
            name='sayere_mazaya',
        ),
        migrations.RemoveField(
            model_name='fish',
            name='vam',
        ),
        migrations.AddField(
            model_name='fish',
            name='bime_azad',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='بیمه آزاد'),
        ),
        migrations.AddField(
            model_name='fish',
            name='bime_takmili',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='بیمه تکمیلی'),
        ),
        migrations.AddField(
            model_name='fish',
            name='eslahe_hoghugh',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='اصلاح حقوق'),
        ),
        migrations.AddField(
            model_name='fish',
            name='estelaji',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='استعلاجی'),
        ),
        migrations.AddField(
            model_name='fish',
            name='jarime',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='جریمه'),
        ),
        migrations.AddField(
            model_name='fish',
            name='jome_kari',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='جمعه کاری'),
        ),
        migrations.AddField(
            model_name='fish',
            name='kasre_hoghugh',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='کسر حقوق'),
        ),
        migrations.AddField(
            model_name='fish',
            name='morakhasi',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='مرخصی'),
        ),
        migrations.AddField(
            model_name='fish',
            name='nemidunam',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='??'),
        ),
        migrations.AddField(
            model_name='fish',
            name='ovlad_moavaghe',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='اولاد معوقه'),
        ),
        migrations.AddField(
            model_name='fish',
            name='paye_sanavat',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='پایه سنوات'),
        ),
        migrations.AddField(
            model_name='fish',
            name='pool_khurd',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='پول خورد'),
        ),
        migrations.AddField(
            model_name='fish',
            name='randeman',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='راندمان'),
        ),
        migrations.AddField(
            model_name='fish',
            name='ravande_mahe_ghabl',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='روند ماه قبل'),
        ),
        migrations.AddField(
            model_name='fish',
            name='vame_aghsati',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='وام اقساطی'),
        ),
        migrations.AddField(
            model_name='fish',
            name='vame_dakheli',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='وام داخلی'),
        ),
    ]
