# Generated by Django 3.2.6 on 2022-06-28 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20220628_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='fish',
            name='ezafe_kar_time',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='اضافه کار'),
        ),
    ]
