# Generated by Django 3.2.6 on 2022-06-28 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_fish_ezafe_kar_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='fish',
            name='mande_morakhasi',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='مانده مرخصی'),
        ),
    ]
