# Generated by Django 3.2.6 on 2022-07-02 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_fish_shekayat'),
    ]

    operations = [
        migrations.AddField(
            model_name='fish',
            name='sal',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='خالص پرداختی'),
        ),
    ]
