# Generated by Django 3.2.6 on 2023-07-23 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_fish_sal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pid', models.IntegerField()),
                ('PNumber', models.BigIntegerField()),
                ('CpCode', models.IntegerField()),
                ('BranchCode', models.IntegerField()),
                ('CardNo', models.IntegerField(blank=True, null=True)),
                ('FName', models.CharField(blank=True, max_length=40, null=True)),
                ('LName', models.CharField(blank=True, max_length=50, null=True)),
                ('NCode', models.CharField(blank=True, max_length=10, null=True)),
                ('BirthDate', models.CharField(blank=True, max_length=10, null=True)),
                ('Father', models.CharField(blank=True, max_length=30, null=True)),
                ('IdCardNo', models.BigIntegerField(blank=True, null=True)),
                ('IssuedFrom', models.CharField(blank=True, max_length=30, null=True)),
                ('BirthPlace', models.CharField(blank=True, max_length=30, null=True)),
                ('Gender', models.CharField(blank=True, max_length=1, null=True)),
                ('Nationality', models.SmallIntegerField(blank=True, null=True)),
                ('Country', models.CharField(blank=True, max_length=20, null=True)),
                ('Tel', models.CharField(blank=True, max_length=12, null=True)),
                ('Mobile', models.CharField(blank=True, max_length=11, null=True)),
                ('PostalCode', models.BigIntegerField(blank=True, null=True)),
                ('Address', models.CharField(blank=True, max_length=200, null=True)),
                ('Kol', models.IntegerField(blank=True, null=True)),
                ('Moin', models.IntegerField(blank=True, null=True)),
                ('GTaf', models.IntegerField(blank=True, null=True)),
                ('CTaf', models.IntegerField(blank=True, null=True)),
                ('Markaz', models.IntegerField(blank=True, null=True)),
                ('Dayere', models.IntegerField(blank=True, null=True)),
                ('Picture', models.ImageField(blank=True, null=True, upload_to='')),
                ('GruopCode', models.CharField(blank=True, max_length=12, null=True)),
                ('OrganizCode', models.CharField(blank=True, max_length=20, null=True)),
                ('TempEmploymentDate', models.CharField(blank=True, max_length=10, null=True)),
                ('PermanentEmplymentDate', models.CharField(blank=True, max_length=10, null=True)),
                ('Ekhrajdate', models.CharField(blank=True, max_length=10, null=True)),
                ('ContractStartDate', models.CharField(blank=True, max_length=10, null=True)),
                ('ContractFinishDate', models.CharField(blank=True, max_length=10, null=True)),
                ('LeaveWorkDate', models.CharField(blank=True, max_length=10, null=True)),
                ('RetiredDate', models.CharField(blank=True, max_length=10, null=True)),
                ('DieDate', models.CharField(blank=True, max_length=10, null=True)),
                ('InsuranceDate', models.CharField(blank=True, max_length=10, null=True)),
                ('Consideration', models.CharField(blank=True, max_length=250, null=True)),
                ('InsuranceNo', models.CharField(blank=True, max_length=10, null=True)),
                ('InsuranceType', models.SmallIntegerField(blank=True, null=True)),
                ('isActive', models.BooleanField(blank=True, null=True)),
                ('FNameEn', models.CharField(blank=True, max_length=40, null=True)),
                ('LNameEn', models.CharField(blank=True, max_length=50, null=True)),
                ('Countryid', models.SmallIntegerField(blank=True, null=True)),
                ('SanavatMonth', models.SmallIntegerField(blank=True, null=True)),
                ('CpCodeSanad', models.IntegerField(blank=True, null=True)),
                ('WebPass', models.CharField(blank=True, max_length=100, null=True)),
                ('TelegramNumber', models.CharField(blank=True, max_length=11, null=True)),
            ],
        ),
    ]
