# Generated by Django 3.2.6 on 2023-08-05 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_personelfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='personelfile',
            name='msgFiledtype',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
