# Generated by Django 3.2.6 on 2023-09-18 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_auto_20230918_1324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personnel',
            name='Shift',
        ),
    ]
