# Generated by Django 3.2.6 on 2023-09-22 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_auto_20230922_1057'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hozurghiab',
            old_name='ghayeb',
            new_name='hozur',
        ),
    ]
