# Generated by Django 3.2.6 on 2023-10-05 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_auto_20231005_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnel',
            name='Pid',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
