# Generated by Django 3.2.6 on 2023-10-05 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_alter_personnel_pid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnel',
            name='Pid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
