# Generated by Django 3.2.6 on 2023-10-05 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_alter_personnel_pid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnel',
            name='BranchCode',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='CpCode',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
