# Generated by Django 3.2.6 on 2023-10-10 11:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_auto_20231005_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hozurghiab',
            name='hdate',
            field=models.DateField(default=datetime.date(2023, 10, 10)),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='PNumber',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
