# Generated by Django 3.2.6 on 2023-10-11 05:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_auto_20231010_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnel',
            name='title',
            field=models.IntegerField(blank=True, choices=[(0, 'سرشیفت'), (1, 'مقدمات'), (2, 'پاساژ'), (3, 'فبنیشر'), (4, 'سردافر'), (5, 'رینگ'), (6, 'لاکنی'), (7, 'دولاتاب'), (8, 'اتوکنر'), (9, 'خدمات'), (10, 'ssm'), (11, 'هیت ست'), (12, 'تاپس'), (13, 'ریبریکر')], null=True),
        ),
        migrations.AlterField(
            model_name='hozurghiab',
            name='hdate',
            field=models.DateField(default=datetime.date(2023, 10, 11)),
        ),
    ]
