# Generated by Django 3.2.6 on 2023-10-21 17:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_auto_20231011_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='hozurghiab',
            name='is_ezafekar',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='hozurghiab',
            name='hdate',
            field=models.DateField(default=datetime.date(2023, 10, 21)),
        ),
        migrations.AlterField(
            model_name='hozurghiab',
            name='title',
            field=models.IntegerField(blank=True, choices=[(0, 'سرشیفت'), (1, 'مقدمات'), (2, 'پاساژ'), (3, 'فبنیشر'), (4, 'سردافر'), (5, 'رینگ'), (6, 'لاکنی'), (7, 'دولاتاب'), (8, 'اتوکنر'), (9, 'خدمات'), (10, 'ssm'), (11, 'هیت ست'), (12, 'تاپس'), (13, 'سرپرست'), (14, 'آزمایشگاه'), (15, 'رنگکشی'), (16, 'آبگیر'), (17, 'کوب'), (18, 'رزرو دیگ'), (19, 'استلام'), (20, 'کوب کوچک'), (21, 'لیفتراک'), (22, 'پرس ضایعات'), (23, 'پرس و خشک کن'), (24, 'لیفتراک ریسندگی'), (25, 'کاردینگ'), (26, 'ریبریکر')], null=True),
        ),
    ]
