# Generated by Django 3.2.6 on 2023-10-21 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_auto_20231021_2121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hozurghiab',
            name='is_ezafekar',
        ),
    ]
