# Generated by Django 3.2.6 on 2024-05-27 06:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0029_hozurghiab_is_ezafekar'),
    ]

    operations = [
        migrations.AddField(
            model_name='fish',
            name='haghe_tahol',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='حق تاهل'),
        ),
        migrations.AddField(
            model_name='fish',
            name='tatil_kar',
            field=models.CharField(default='0', max_length=255, verbose_name='تعطیل کار'),
        ),
        migrations.AlterField(
            model_name='hozurghiab',
            name='hdate',
            field=models.DateField(default=datetime.date(2024, 5, 27)),
        ),
    ]
