# Generated by Django 3.2.6 on 2024-05-27 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0030_auto_20240527_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fish',
            name='haghe_tahol',
            field=models.CharField(default='0', max_length=255, verbose_name='حق تاهل'),
        ),
    ]
